# Site settings
title: Brainstem Breakfast
email: brainstembreakfast@outlook.com
description: "Programming nuggets for your brain"
baseurl: ""
url: "http://brainstembreakfast.com"
twitter_username: brianrackle
github_username:  brianrackle
highlighter: pygments
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

authors:
  brian:
    display_name: Brian Rackle
    gravatar: 6bece3435bb5ac00c81c6e6468d15993
    twitter: brianrackle
    github: brianrackle

