# Site settings
title: Brainstem Breakfast
email: rackle@outlook.com
description: "Programming nuggets everyday"
baseurl: ""
url: "http://brainstembreakfast.com"
twitter_username: brianrackle
github_username:  brianrackle
highlighter: pygments
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

